export const javascriptTopics = [
  "Blueprint",
  "CAD (Computer-Aided Design)",
  "Elevation",
  "Floor Plan",
  "Section",
  "Rendering",
  "Facade",
  "Setback",
  "Zoning",
  "Site Plan",
  "Structural Engineer",
  "Massing",
  "Schematic Design",
  "Building Code",
  "Permit",
  "Sustainability",
  "Load-bearing Wall",
  "Plinth",
  "Lintel",
  "Beam",
  "Column",
  "Cantilever",
  "Fenestration",
  "Cladding",
  "Bracing",
  "Footing",
  "Skylight",
  "Atrium",
  "Egress",
  "Parapet",
  "Insulation",
  "HVAC (Heating, Ventilation, and Air Conditioning)",
  "Hardscape",
  "Softscape",
  "Urban Planning",
  "LEED (Leadership in Energy and Environmental Design)",
  "Modular Design",
  "Space Planning",
  "Ergonomics",
  "Facade Treatment",
  "Contextual Architecture",
  "Passive Solar Design",
  "Load Path",
  "Revit",
  "BIM (Building Information Modeling)",
  "Tensile Structure",
  "Green Roof",
  "Fire Safety",
  "As-built Drawings",
  "Building Envelope",
];

export const c_cppTopics = [
  "Mood Board",
  "Space Planning",
  "Focal Point",
  "Color Palette",
  "Accent Wall",
  "Texture",
  "Pattern",
  "Balance",
  "Scale",
  "Proportion",
  "Symmetry",
  "Asymmetry",
  "Rhythm",
  "Contrast",
  "Harmony",
  "Ambient Lighting",
  "Task Lighting",
  "Accent Lighting",
  "Lumens",
  "Furniture Layout",
  "Ergonomics",
  "Flooring",
  "Window Treatments",
  "Upholstery",
  "Wallcovering",
  "Crown Molding",
  "Baseboard",
  "Wainscoting",
  "Cabinetry",
  "Shelving",
  "Soft Furnishings",
  "Drapery",
  "Curtains",
  "Blinds",
  "Room Flow",
  "Open Concept",
  "Minimalism",
  "Maximalism",
  "Eclectic",
  "Bohemian",
  "Modern",
  "Mid-century Modern",
  "Transitional",
  "Traditional",
  "Rustic",
  "Industrial",
  "Feng Shui",
  "Mood Lighting",
  "Sustainable Design",
  "Custom Joinery",
  "Accessories",
];

export const pythonTopics = [
  "Hardscape",
  "Softscape",
  "Landscape Design",
  "Curb Appeal",
  "Pergola",
  "Gazebo",
  "Patio",
  "Decking",
  "Paver",
  "Retaining Wall",
  "Driveway",
  "Walkway",
  "Pathway",
  "Fence",
  "Gate",
  "Arbor",
  "Trellis",
  "Grading",
  "Drainage",
  "Xeriscaping",
  "Irrigation",
  "Planting Plan",
  "Shrubs",
  "Perennials",
  "Annuals",
  "Ground Cover",
  "Mulch",
  "Garden Bed",
  "Water Feature",
  "Pond",
  "Fountain",
  "Outdoor Lighting",
  "Landscape Lighting",
  "Pergola",
  "Outdoor Kitchen",
  "Fire Pit",
  "Outdoor Furniture",
  "Shade Structure",
  "Gutter",
  "Roofline",
  "Siding",
  "Cladding",
  "Eaves",
  "Soffit",
  "Fascia",
  "Facade",
  "Stone Veneer",
  "Stucco",
  "Brickwork",
  "Sustainable Landscape",
  "Rainwater Harvesting",
];

export const nodeExpressTopics = [
  "Aesthetic Value",
  "Design Criteria",
  "Structural Integrity",
  "Load Capacity",
  "Dynamic Load",
  "Static Load",
  "Shear Wall",
  "Foundation Settlement",
  "Compaction",
  "Geosynthetics",
  "Lateral Load",
  "Earthquake Engineering",
  "Structural Retrofit",
  "Construction Safety",
  "Project Scheduling",
  "Cost Estimation",
  "Materials Science",
  "Construction Drawings",
  "Civil Engineering Codes",
  "Environmental Impact",
  "Site Assessment",
  "Building Envelope",
  "Landscape Architecture",
  "Site Planning",
  "Outdoor Living Space",
  "Hardscaping",
  "Site Amenities",
  "Terracing",
  "Storm Drainage",
  "Green Infrastructure",
  "Urban Design",
  "Outdoor Renovation",
  "Land Use Planning",
  "Accessibility Design",
  "Facade Restoration",
  "Building Maintenance",
  "Energy Efficiency",
  "Interior Finishes",
  "Spatial Planning",
  "Furniture Layout",
  "Visual Comfort",
  "Ceiling Design",
  "Flooring Options",
  "Wall Treatments",
  "Architectural Style",
  "Room Acoustics",
  "Space Optimization",
  "Design Ergonomics",
  "Adaptive Reuse",
  "Thermal Comfort",
];

export const reactTopics = [
  "Blueprint",
  "Structural Load",
  "Foundation",
  "Footing",
  "Reinforced Concrete",
  "Steel Reinforcement",
  "Bearing Capacity",
  "Geotechnical Engineering",
  "Soil Testing",
  "Excavation",
  "Surveying",
  "Topography",
  "Contour Lines",
  "Elevation",
  "Retaining Wall",
  "Beam",
  "Column",
  "Slab",
  "Shear Force",
  "Moment of Inertia",
  "Load Distribution",
  "Seismic Design",
  "Hydraulics",
  "Drainage System",
  "Water Table",
  "Stormwater Management",
  "Pavement Design",
  "Roadway",
  "Bridge",
  "Tunnel",
  "Construction Management",
  "Project Lifecycle",
  "Building Code",
  "Permit",
  "Material Testing",
  "Structural Analysis",
  "Finite Element Analysis",
  "Concrete Mix Design",
  "Civil Engineering Software",
  "AutoCAD",
  "BIM (Building Information Modeling)",
  "Blueprint Reading",
  "Site Development",
  "Load-bearing Wall",
  "Vibration Analysis",
  "Structural Integrity",
  "Sustainable Construction",
];
