import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./App.css";
import Header from "@/components/ui/myComponents/Header";
import Footer from "@/components/ui/myComponents/Footer";
import Authprovider from "@/components/ui/myComponents/Authprovider/Authprovider";
import TanstackProvider from "@/providers/TanstackProvider";
import { ThemeModeScript } from "flowbite-react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arcline Designs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <TanstackProvider>
          <Authprovider>
            <div className="top-0 left-0 sticky z-50">
              <Header />
            </div>
            <div>{children}</div>
            <div className="h-[274px]">
              <Footer />
            </div>
          </Authprovider>
        </TanstackProvider>
      </body>
    </html>
  );
}
