import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./App.css";
import Header from "@/components/ui/myComponents/Header";
import Footer from "@/components/ui/myComponents/Footer";
// import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Provider store={store}> */}
        <body className={inter.className}>
          <div>
            <Header />
          </div>
          <div>{children}</div>
          <div>
            <Footer />
          </div>
        </body>
      {/* </Provider> */}
    </html>
  );
}
